network: story
folder: '.story/story'
daemon: story
chain_id: story-1
node_version: v0.13.0
repo: 'https://github.com/piplabs/story'
custom_port_prefix: 292
genesis: 'https://raw.githubusercontent.com/cosmos/testnets/master/replicated-security/ethera_9000-1/ethera_9000-1-genesis.json'
peers: 'c1d973eea1b2c637777ab32783b3d37f2b52ba36@b1.storyrpc.io:26656,78db197dbbffb97a5c851b87b1df4cc51e99d4f9@b2.storyrpc.io:26656'
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
